//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Myservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Myservice.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WsOperation", ReplyAction="http://tempuri.org/IService1/WsOperationResponse")]
        string[] WsOperation(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WsOperation", ReplyAction="http://tempuri.org/IService1/WsOperationResponse")]
        System.Threading.Tasks.Task<string[]> WsOperationAsync(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WeatherService", ReplyAction="http://tempuri.org/IService1/WeatherServiceResponse")]
        string[] WeatherService(string zipcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WeatherService", ReplyAction="http://tempuri.org/IService1/WeatherServiceResponse")]
        System.Threading.Tasks.Task<string[]> WeatherServiceAsync(string zipcode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication1.Myservice.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication1.Myservice.IService1>, WebApplication1.Myservice.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] WsOperation(string url) {
            return base.Channel.WsOperation(url);
        }
        
        public System.Threading.Tasks.Task<string[]> WsOperationAsync(string url) {
            return base.Channel.WsOperationAsync(url);
        }
        
        public string[] WeatherService(string zipcode) {
            return base.Channel.WeatherService(zipcode);
        }
        
        public System.Threading.Tasks.Task<string[]> WeatherServiceAsync(string zipcode) {
            return base.Channel.WeatherServiceAsync(zipcode);
        }
    }
}
